### ISSUE TITLE
Instantiation opens socket immediately

### ISSUE THREAD

**Issue by jamesloewen** [pladaria/reconnecting-websocket#102]
Would be an enhancement request. I have a case where I want to declare the socket but only open it if navigated to a specific section of our website. However, as currently configured it attempts to connect immediately.

Would we be able to have a `socket.open` API added and corresponding `automaticOpen` config available? Or something along those lines? Would make usage a lot more flexible

**Comment by dawnmist** [comment]
I'm facing the same thing at the moment.

My initial work-around is to call `websocket.close()` immediately after creating the socket. It sets a flag that stops the automatic open process before it completes, and it doesn't continue to try to connect.

Then when I want to use it, I'm calling `websocket.reconnect()`.

The issue I'm finding is to do with the connection timings on reconnect. If I want it to try to connect immediately, I want a small value for the option `minReconnectionDelay`. The issue is that this small value is also used as-is for the delay for the second connection attempt if the initial connection fails, i.e. in the `_getNextDelay()` function, the first connection has a `_retryCount` value of 0 - so the `minReconnectionDelay` value is used. On the second connection attempt the `_retryCount` value is 1, which results in the delay being set to:
```
minReconnectionDelay * Math.pow(reconnectionDelayGrowFactor, this._retryCount - 1) 
 = minReconnectionDelay * Math.pow(reconnectionDelayGrowFactor, 0)
 = minReconnectionDelay * 1
```
It means that the second connection attempt cannot be given any delay longer than the initial attempt, making it impossible to have a "connect immediately but don't immediately spam reconnection if that fails".

What I'd really like to do is set the initial attempt to occur immediately, then all attempts after that to have a 10s delay. To be able to do that, the formula would need to be changed so that it no longer subtracts 1 from the `_retryCount` when using Math.pow - or it would need to set a separate value for initial delay so that minReconnectionDelay was used only for second/third/etc connection attempts but not for the initial one.

**Comment by pladaria** [comment]
Hi, thank you for your comments. I've added a `startClosed` option
```js
const ws = new ReconnectingWebSocket(URL, anyProtocol, {
    startClosed: true,
});

...

ws.reconnect(); // to start connection at any moment
```

Will be available on next release
